/**
 * Idempotent seed ingest — run any time to (re)build MongoDB.
 * Usage: npm run ingest
 *
 * D10 — relationships by _id. Collections: difficulties, topics, patterns,
 * problems (approaches + presets EMBEDDED), traces (gzip-compressed, D11), sheets.
 *
 * NOTE (transitional): trace STEPS are currently generated by the existing
 * TypeScript tracers (lib/tracers). The hybrid Python tracer (D9) will replace
 * this step-generation source via per-problem authoring bundles (rules/Authoring.md)
 * WITHOUT changing the stored schema below — so the app keeps running through the
 * migration. Metadata still comes from the fixture / JSON sources for now.
 */
import { loadEnvConfig } from "@next/env";
import { MongoClient, ObjectId, type Db } from "mongodb";
import { gzipSync } from "zlib";
import fs from "fs";
import path from "path";

loadEnvConfig(process.cwd());

const SEEDS_DIR = path.join(process.cwd(), "seeds");
const PROBLEMS_DIR = path.join(SEEDS_DIR, "problems");
const DB_NAME = "knacktor";
const TRACE_VERSION = "1.0.0";

interface SeedDoc {
  slug: string;
  [key: string]: unknown;
}

// ── Indexes ────────────────────────────────────────────────────────────────
async function setupIndexes(db: Db) {
  for (const col of ["difficulties", "topics", "patterns", "sheets"] as const) {
    await db.collection(col).createIndex({ slug: 1 }, { unique: true });
  }
  const problems = db.collection("problems");
  await problems.createIndex({ slug: 1 }, { unique: true });
  await problems.createIndex({ difficultyId: 1 });
  await problems.createIndex({ topicIds: 1 });
  await problems.createIndex({ patternIds: 1 });
  await problems.createIndex({ number: 1 });
  await problems.createIndex(
    { title: "text", statement: "text" },
    { name: "problems_text_search" }
  );

  const traces = db.collection("traces");
  await traces.createIndex({ problemId: 1, approachId: 1, inputId: 1 }, { unique: true });
  await traces.createIndex({ problemSlug: 1, approachId: 1 });
  console.log("  ✓ indexes ready");
}

// ── Generic slug-keyed seed loader; returns slug -> _id map ──────────────────
async function seedCollection(
  db: Db,
  col: string,
  file: string
): Promise<Map<string, string>> {
  const map = new Map<string, string>();
  if (!fs.existsSync(file)) {
    console.log(`  — seeds/${path.basename(file)} not found, skipping`);
    return map;
  }
  const docs: SeedDoc[] = JSON.parse(fs.readFileSync(file, "utf-8"));
  const now = new Date();
  for (const { slug, ...rest } of docs) {
    await db.collection(col).updateOne(
      { slug },
      { $set: { ...rest, slug, updatedAt: now }, $setOnInsert: { createdAt: now } },
      { upsert: true }
    );
    const doc = await db.collection(col).findOne({ slug }, { projection: { _id: 1 } });
    map.set(slug, (doc!._id as ObjectId).toHexString());
  }
  console.log(`  ↑ ${col}: ${docs.length}`);
  return map;
}

// ── Problem source (metadata) — fixture or JSON, normalized to ProblemFull-ish ─
interface ProblemSource {
  slug: string;
  number: number;
  title: string;
  difficulty: string;
  topics: string[];
  patterns: string[];
  statement: string;
  recommendedApproachId: string;
  supportsCustomInput: boolean;
  supportsCompare: boolean;
  inputConstraints?: unknown;
  approaches: Array<{ id: string; kind: string; [k: string]: unknown }>;
  presetInputs: Array<{ id: string; value: unknown; [k: string]: unknown }>;
}

function resolveIds(slugs: string[], map: Map<string, string>, kind: string): ObjectId[] {
  return slugs.map((s) => {
    const id = map.get(s);
    if (!id) throw new Error(`unknown ${kind} slug "${s}" — add it to seeds/${kind}.json`);
    return new ObjectId(id);
  });
}

async function ingestProblem(
  db: Db,
  src: ProblemSource,
  maps: { diff: Map<string, string>; topic: Map<string, string>; pattern: Map<string, string> },
  TRACERS: Record<string, Record<string, (input: unknown) => { steps: { i: number; isKeyEvent?: boolean }[]; finalResult: unknown }>>
): Promise<number> {
  const now = new Date();
  const difficultyId = resolveIds([src.difficulty], maps.diff, "difficulties")[0];
  const topicIds = resolveIds(src.topics, maps.topic, "topics");
  const patternIds = resolveIds(src.patterns, maps.pattern, "patterns");

  await db.collection("problems").updateOne(
    { slug: src.slug },
    {
      $set: {
        slug: src.slug,
        number: src.number,
        title: src.title,
        difficultyId,
        topicIds,
        patternIds,
        statement: src.statement,
        hasVisualization: true,
        isPremium: false,
        supportsCustomInput: src.supportsCustomInput,
        supportsCompare: src.supportsCompare,
        recommendedApproachId: src.recommendedApproachId,
        approaches: src.approaches,
        presetInputs: src.presetInputs,
        inputConstraints: src.inputConstraints,
        schemaVersion: "2.0",
        updatedAt: now,
      },
      $setOnInsert: { createdAt: now },
    },
    { upsert: true }
  );
  const problemDoc = await db.collection("problems").findOne({ slug: src.slug }, { projection: { _id: 1 } });
  const problemId = problemDoc!._id as ObjectId;
  console.log(`  ↑ problems/${src.slug}`);

  let traceCount = 0;
  for (const approach of src.approaches) {
    const builder = TRACERS[src.slug]?.[approach.id];
    if (!builder) {
      console.log(`    — no tracer for ${src.slug}:${approach.id}, skipping traces`);
      continue;
    }
    for (const preset of src.presetInputs) {
      let steps, finalResult;
      try {
        ({ steps, finalResult } = builder(preset.value));
      } catch (err) {
        throw new Error(
          `trace failed for ${src.slug}:${approach.id}:${preset.id}: ${err instanceof Error ? err.message : err}`
        );
      }
      const keyEventIndices = steps.filter((s) => s.isKeyEvent).map((s) => s.i);
      const compressed = gzipSync(Buffer.from(JSON.stringify(steps), "utf-8"));
      await db.collection("traces").updateOne(
        { problemId, approachId: approach.id, inputId: preset.id },
        {
          $set: {
            problemId,
            problemSlug: src.slug,
            approachId: approach.id,
            inputId: preset.id,
            stepCount: steps.length,
            keyEventIndices,
            finalResult,
            compression: "gzip",
            stepsCompressed: compressed,
            byteSize: compressed.length,
            traceVersion: TRACE_VERSION,
            updatedAt: now,
          },
          $setOnInsert: { createdAt: now },
        },
        { upsert: true }
      );
      console.log(`    ↑ traces/${src.slug}:${approach.id}:${preset.id} (${steps.length} steps, ${(compressed.length / 1024).toFixed(1)}KB gz)`);
      traceCount++;
    }
  }
  return traceCount;
}

// ── Sheets (entries reference problems by _id) ───────────────────────────────
async function seedSheets(db: Db) {
  const file = path.join(SEEDS_DIR, "sheets.json");
  if (!fs.existsSync(file)) return;
  const sheets: Array<{ slug: string; name?: string; description?: string; problemSlugs?: string[] }> =
    JSON.parse(fs.readFileSync(file, "utf-8"));
  if (!Array.isArray(sheets) || sheets.length === 0) return;
  const now = new Date();
  for (const sheet of sheets) {
    const entries = [];
    for (const [order, pslug] of (sheet.problemSlugs ?? []).entries()) {
      const p = await db.collection("problems").findOne({ slug: pslug }, { projection: { _id: 1 } });
      if (p) entries.push({ problemId: p._id, order });
    }
    await db.collection("sheets").updateOne(
      { slug: sheet.slug },
      {
        $set: { slug: sheet.slug, name: sheet.name, description: sheet.description, entries, updatedAt: now },
        $setOnInsert: { createdAt: now },
      },
      { upsert: true }
    );
  }
  console.log(`  ↑ sheets: ${sheets.length}`);
}

async function main() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error("✗ MONGODB_URI not set — add it to .env.local");
    process.exit(1);
  }
  const client = new MongoClient(uri);
  await client.connect();
  console.log("✓ Connected to MongoDB");
  const db = client.db(DB_NAME);

  await setupIndexes(db);

  console.log("\nSeeding taxonomy…");
  const diff = await seedCollection(db, "difficulties", path.join(SEEDS_DIR, "difficulties.json"));
  const topic = await seedCollection(db, "topics", path.join(SEEDS_DIR, "topics.json"));
  const pattern = await seedCollection(db, "patterns", path.join(SEEDS_DIR, "patterns.json"));

  // Tracers + fixture metadata (resolved via @/ alias by tsx)
  const { TRACERS } = await import("../lib/tracers/index");
  const { FOURSUM_PROBLEM } = await import("../lib/fixtures/4sum");

  // Problem sources: 4Sum (fixture) + container (JSON metadata)
  const sources: ProblemSource[] = [FOURSUM_PROBLEM as unknown as ProblemSource];
  const containerFile = path.join(PROBLEMS_DIR, "container-with-most-water.json");
  if (fs.existsSync(containerFile)) {
    const c = JSON.parse(fs.readFileSync(containerFile, "utf-8"));
    // strip embedded hand-written traces — steps come from the TS tracer
    delete c.traces;
    sources.push(c as ProblemSource);
  }

  console.log("\nIngesting problems + traces…");
  let traces = 0;
  for (const src of sources) {
    // Compare requires >= 2 approaches that can actually produce a trace.
    const traceable = src.approaches.filter((a) => TRACERS[src.slug]?.[a.id]).length;
    src.supportsCompare = src.supportsCompare && traceable >= 2;
    traces += await ingestProblem(db, src, { diff, topic, pattern }, TRACERS as never);
  }

  console.log("\nSeeding sheets…");
  await seedSheets(db);

  await client.close();
  console.log(`\n✓ Ingest complete — ${sources.length} problem(s), ${traces} trace(s)`);
}

main().catch((err) => {
  console.error("✗ Ingest failed:", err instanceof Error ? err.message : err);
  process.exit(1);
});
